apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - ./secrets/argocd-secret.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml

patches:
  - path: patches/argocd-secret.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
