apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

resources:
  - namespace.yaml
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.3/controller.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: sealed-secrets
