apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_backuprepositories.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_backups.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_backupstoragelocations.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_deletebackuprequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_downloadrequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_podvolumebackups.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_podvolumerestores.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_restores.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_schedules.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_serverstatusrequests.yaml
  - https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_volumesnapshotlocations.yaml
