apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=master

patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: descheduler-cronjob
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/30 * * * *"
