apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: sealed-secrets-key-schedule
spec:
  # cron形式: 毎日午前3時にバックアップ
  schedule: "0 3 * * *"

  template:
    # バックアップ先のBLSを指定
    storageLocation: sealed-secrets
    # バックアップで含めたいNamespaceを指定
    includedNamespaces:
      - "sealed-secrets"
    # 含めたいリソースを限定 (Secretのみ)
    includedResources:
      - secrets
    # (任意) バックアップの保持期間: 240時間(10日)後に自動削除
    ttl: 240h
